services:
  financial-manager-api:
    image: financial-manager-api:latest
    container_name: financial-manager-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:13.5
    container_name: financial-manager-db
    restart: always
    env_file:
      - docker.env
    volumes:
      - postgres:/var/lib/postgresql/financial-manager
    ports:
      - '5432:5432'

volumes:
  postgres:
    name: nest-db