services:
  financial-manager-db:
    image: postgres:13.5
    container_name: financial-manager-db
    restart: always
    env_file:
      - docker.env
    volumes:
      - postgres:/var/lib/postgresql/financial-manager
    ports:
      - '5432:5432'
    networks:
      - nestjs

  financial-manager-api:
    image: financial-manager-api:latest
    container_name: financial-manager-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - financial-manager-db
    env_file:
      - .env
    networks:
      - nestjs

volumes:
  postgres:
    name: nest-db

networks:
   nestjs: